/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AxiosResponse } from "axios";
import { Expose } from "class-transformer";

export class GetstatusServiceStatus extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "app" })
    app?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "moto" })
    moto?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "notes" })
    notes?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "os" })
    os?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "php_version" })
    phpVersion?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status: string;

    @SpeakeasyMetadata()
    @Expose({ name: "time" })
    time?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "users" })
    users?: number;
}

export class GetstatusResponse extends SpeakeasyBase {
    /**
     * HTTP response content type for this operation
     */
    @SpeakeasyMetadata()
    contentType: string;

    @SpeakeasyMetadata()
    serviceStatus?: GetstatusServiceStatus;

    /**
     * HTTP response status code for this operation
     */
    @SpeakeasyMetadata()
    statusCode: number;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    rawResponse: AxiosResponse;
}
